config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # 與下面路徑是一樣的意思
  # get '/', to: 'candidates#index'
  root 'candidates#index'
  
  # 原本的寫法 -> 不夠直覺
  # get "/history", to: "candidates#history"
  # 比較好的寫法
  get "/history", to: "users#history"

  resources :candidates do
  # member 作法 -> 視為candidate的一部份
    member do
      patch :vote
    end
  end

  # /admin
  namespace :admin do
    root 'pages#index'

    resources :candidates
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  # 加上驗證，名字必填。驗證名字這個欄位是存在。名字沒有寫時，按出送出就會錯了！
  validates :name, presence: true
  # 驗證年紀必填。
  validates :age, numericality: { greater_than_or_equal_to: 40 }

  # 每個候選人可以有很多張選票 用了hasmany(類別方法) 至少可以得到兩個方法
  # votes
  # votes= 
  has_many :votes
  # 透過 has_many 與 user 有關連(虛線)，但實際上要透過 votes 來查詢。
  has_many :users, through: :votes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # 透過 has_many 與 candidates 有關連(虛線)，但實際上要透過 votes 來查詢。
  has_many :votes
  has_many :candidates, through: :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidate, counter_cache: "vote"
  belongs_to :user
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # before_action(在action之前 做某件事情):是個類別方法
  # 舊專案(rails 4)可以看這樣的程式碼(以前的用法) before_filler :ind_candidate
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]
  # Devise使用的before_action，怎麼使用：看文件。
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # 給一個變數(複數) = 找出所有候選人的列表
    # @candidates = Candidate.all
    # 一頁顯示三個
    @candidates = Candidate.all.page(params[:page]).per(3)
  end
  
  # 如果要去資料庫撈東西時，controller 裡還是要寫 show 的 action 
  # http://localhost:3000/candidates/1 -> routes 長的樣子 /candidate/:id
  def show
    # 如果要給view使用的話 記得要加 @，如果不要的話 就不要@(區域變數)
    # @candidate = Candidate.where(id: params[:id]).last 這是比較笨的做法之一
    # @candidate = Candidate.find(params[:id]) 只能找id
    # @candidate = Candidate.find_by(id: params[:id]) 比較有彈性
    # 在 SQL的語法 select * from candidate where id =? 
  end

  def new
    # 要在controller上做完，不要在views上做事情
    @candidate = Candidate.new
  end

  # create是個沒有畫面的方法
  def create
    @candidate = Candidate.new(candidate_params)

    # 假如儲存成功時會轉到首頁
    if @candidate.save
      redirect_to root_path, notice: '新增成功' 
    else
      # render action: :new 的縮寫
      # render file: '../views/candidates/new.html.erb'
      # 我要去借 new 的template
      render :new
    end
  end

  # /candidates/1/edit -> routes 長的樣子 /candidate/:id/edit
  def edit
    # redirect_to root_path, alert: '需要登入' if not user_signed_in?
    # redirect_to root_path, alert: '需要登入' unless not user_signed_in? 剛上面一樣的效果
  end

  # patch /candidates/2
  def update

    if @candidate.update(candidate_params)
      redirect_to root_path, notice: '更新成功'
    else
      render :edit
    end
  end

  # delete /candidates/:id
  def destroy
    @candidate.destroy
    redirect_to root_path, notice: '資料已刪除'
  end
  
  def vote
    # 從候選人的角度來新增,這個時候還沒有 vote 這個model
    # @candidate.votes.create(ip_address: request.remote_ip)

    # 從登入者的角度來新增，程式碼比較讓人容易懂
    current_user.votes.create(ip_address: request.remote_ip, candidate: @candidate)

    # 從候選人的角度來新增
    # @candidate.votes.create(ip_address: request.remote_ip, user: current_user)
    redirect_to root_path, notice: '投票完成'

    # 從票的角度
    # Vote.create(candidate_id: @candidate.id, ip_address: request.remote_ip) 這樣才對
    # Vote.create(candidate: @candidate, ip_address: request.remote_ip)
    # redirect_to root_path, notice: '投票完成'
  end

  # private也是個方法
  private
  
  # 重複的程式碼 寫成方法 可重複使用。
  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end

  def candidate_params
    # 用實體變數接起來，用params去抓一群東西(姓名、黨派......)
    # "candidate"=>{"name"=>"111", "age"=>"111", "party"=>"111", "platform"=>"111"}
    # permit 是個清洗的方法
    candidate_params = params.require(:candidate).permit(:name, :age, :party, :platform)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

# 跟上面是一樣的效果
#   def home
#     render file: '../views/pages/home.html.erb'
#   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Devise使用的before_action，怎麼使用：看文件。
  before_action :authenticate_user!
  def history
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message(msg_type)
    "<p class='#{msg_type}'>#{flash[msg_type]}</p>".html_safe
    # 長出來的內容
    # <p class="notice"><%= notice %></p>
    # <p class="alert"><%= alert %></p>
  end

  def delete_link_to(label, url)
    link_to label, url, class: 'destroy btn', method: 'delete', data: { confirm: '確認刪除?!'}
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
  def say_hello_to(someone)
    "哈囉 #{someone}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/index.html.erb
<h1>後臺首頁</h1>

app/views/candidates/_form.html.erb
<!-- 先下判斷 是否為一個候選人的物件 -->
<% if candidate.is_a?(Candidate) %>

  <!-- 當欄位沒填好時，就跑這個判斷 -->
  <% if candidate.errors.any? %>
  <ul>
    <% candidate.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_for(candidate, html: {id: 'candidate_form' }) do |form| %>
  <div>
    <%= form.label :name, '姓名' %>
    <!-- <input type="text" name="name" id="name"> 原本的寫法--> 
    <%= form.text_field :name %>
  </div>
  <div>
    <!-- <label for="age">年齡</label>原本的寫法 -->
    <%= form.label :age, '年齡' %>
    <%= form.text_field :age %>
  </div>
  <div>
    <%= form.label :party, '黨派' %>
    <%= form.text_field :party %>
  </div>
  <div>
    <%= form.label :platform, '政見' %>
    <%= form.text_area :platform %>
  </div>
    <!-- <input type="submit" value="新增候選人"> 原來的寫法 -->
  <%= form.submit %>
  <% end %>

<% end %>

app/views/candidates/edit.html.erb
<h1>更新候選人資料</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>
<!-- <a href="/candidates/new">新增候選人</a> 原本的寫法 -->
<!-- 第一個參數字樣 第二個參數連結 -->
<!-- new_candidate_path 及 link_to 是方法 -->
<%= link_to "新增候選人", new_candidate_path %>

<div class="candidate-list">
    <%= paginate @candidates %>
    <!-- 這個 candidate 是在 controller 裡的 index 抓到所有候選人的名單 -->
    <% @candidates.each do |candidate| %>
    <!-- 候選人start -->
    <div class="candidate-card">
        <div class="avater">
            <img src="https://images.pexels.com/photos/57416/cat-sweet-kitty-animals-57416.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260">
        </div>
        <div class="info">
            <!-- h1及h2 的內容不能寫死，因為候選人是不相同的,透過each的方式去資料庫抓出資料，有幾個就跑出幾個-->
            <!-- 記得 candidate不要加＠,來源是從上面的迴圈跑出來的 |candidate| -->
            <h1>候選人：<%= candidate.name %>(<%= candidate.age %>)</h1>
            <h2>政黨：<%= candidate.party %></h2>
            <h2>得票數：<%= candidate.vote %></h2>
            <!-- <a href="/candidate/<%= candidate.id %>" class="more-detail">看政見</a> html原本的寫法 -->
            <!-- <%= link_to "看政見", candidate_path(candidate.id), class:"more-detail" %> rails 最原始的寫法-->
            <%= link_to "政見", candidate, class: 'btn more-detail' %>
            <%= link_to "投票", vote_candidate_path(candidate), method: 'patch', class: 'btn vote', data: { confirm: '確定進行投票嗎?!'} if user_signed_in?  %>
            <%= link_to "修改", edit_candidate_path(candidate), class: 'btn update' if user_signed_in? %>
            <%= delete_link_to "刪除", candidate %>
        </div>
    </div>
    <!-- 候選人end -->
    <% end %>
</div>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>
<%= link_to "回候選人列表", root_path %>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<!-- 切記不要在view上去撈資料 這些都是controller的事情, 雖然view是可以做到撈資料這件事情 -->
<h1><%= @candidate.name %></h1>
<ul>
    <li>年齡：<%= @candidate.age %></li>
    <li>黨派：<%= @candidate.party %></li>
    <!-- 加上simple_format 就可以把newline轉換成br -->
    <li>政見：<%= simple_format(@candidate.platform)%></li>
</ul>

<%= link_to "回候選人列表", root_path %>

<ul>
<!-- 找出每個候選人有多少張票 因為會產生n+1的問題，所以改成user -->
  <% @candidate.users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<!-- 從heleper過來的 -->
<%= flash_message(:alert) %>
<%= flash_message(:notice) %>

<!-- <%= flash[:notice] %> 可以改成下面的寫法 -->
<!-- <p class="notice"><%= notice %></p> -->
<!-- <p class="alert"><%= alert %></p> -->

app/views/shared/_nav.html.erb
  <nav class="top-nav">
    <ul>
        <li><%= link_to "首頁", root_path %></li>
        <% if user_signed_in? %>
          <!-- <li>hi, ...Email</li> html 原本的寫法 -->
          <!-- user物件 使用email欄位  -->
          <li>hi, <%= current_user.email %></li>
          <!-- <li><a href="">登出</a></li> html 原本的寫法 -->
          <li><%= link_to "登出", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <!-- <li><a href="#">登入</a></li> html 原本的寫法 -->
          <li><%= link_to "登入", new_user_session_path %></li>
          <!-- <li><a href="#">註冊</a></li> html 原本的寫法 -->
          <li><%= link_to "註冊", new_user_registration_path %></li>
        <% end %>
        </ul>
  </nav>

app/views/users/history.html.erb
<% current_user.votes.each do |vote| %>
  <li><%= vote.ip_address %> <%= vote.created_at %></li>
<% end %>